### ISSUE TITLE
How can I use my GPU 😂

### ISSUE THREAD

**Issue by loveandbeepbrother** [guidance-ai/guidance#536]
**The bug**
I used the 0.15 version of guidance, and the compiled version of the current source code. But no matter how I adjust the value of the device parameter, (0, 'auto', 'gpu', etc.) 
every time the model is loaded in the memory and the following error is reported:
```python
ValueError: Found modules on cpu/disk. 
Using Exllama or Exllamav2 backend requires all the modules to be on GPU.You can deactivate exllama backend by setting `disable_exllama=True` in the quantization config object
```

I use the A30, Driver Version: 515.65.01 CUDA Version: 11.7,torch ==2.0.1
```python
import guidance
from transformers import AutoModelForCausalLM, AutoTokenizer
model_path = "Qwen-14B-Chat-Int4"

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
guidance.llm = guidance.models.Transformers(model_path,tokenizer,device=0, trust_remote_code=True)
```
P.S: torch.cuda.is_available() = True
**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.):ubuntu 18.04
 - Guidance Version (`guidance.__version__`):0.1.5\0.1.7

**Comment by slundberg** [comment]
Have you tried loading the same model with vanilla transformers? If that works but the guidance load fails let us know :)

**Comment by loveandbeepbrother** [comment]
> Have you tried loading the same model with vanilla transformers? If that works but the guidance load fails let us know :)  

yeah,I tried them in same notebook
```python
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", trust_remote_code=True).eval()
model.generation_config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True)
```

```python
import guidance
from transformers import AutoModelForCausalLM, AutoTokenizer
model_path = "Qwen-14B-Chat-Int4"

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
guidance.llm = guidance.models.Transformers(model_path,tokenizer,device=0, trust_remote_code=True)
```
and only guidance failed😂

**Comment by ambroser53** [comment]
I had this issue as well, guidance doesn't make it very clear because they have a weird "`device`" flag that casts the model to that device after loading it automatically to cpu (which is wrong on so many levels). Saving grace is that guidance allows you to pass whatever you want to the transformers from_pretrained call within kwargs and what your supposed to use is `device_map`. I use `device_map={"":0}` which just always tries to fit the model on the first GPU on the machine. Also don't forget to set your `torch_dtype` to something like `bfloat16` because it'll often load in `float32` by default which is not only overkill but will not fit in most cards for inference.

**Comment by loveandbeepbrother** [comment]
> I had this issue as well, guidance doesn't make it very clear because they have a weird "`device`" flag that casts the model to that device after loading it automatically to cpu (which is wrong on so many levels). Saving grace is that guidance allows you to pass whatever you want to the transformers from_pretrained call within kwargs and what your supposed to use is `device_map`. I use `device_map={"":0}` which just always tries to fit the model on the first GPU on the machine. Also don't forget to set your `torch_dtype` to something like `bfloat16` because it'll often load in `float32` by default which is not only overkill but will not fit in most cards for inference.

IT JUST WORKS!!! Thanks a lot😀

**Comment by jeanibarz** [comment]
Have the same issue. I would prefear to use llama-cpp-python instead of ctransformers to load GGUF quantized models. Do you have some guidance ? I'm running guidance inside a devcontainer. The devcontainer is correctly configured: I have been able to run TTS on GPU on it. I tried the following:
- changed my docker base image, which I know was working fine with my GPU, from `nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04` to `nvidia/cuda:12.1.1-devel-ubuntu22.04`
- uninstalled llama-cpp-python and reinstall it with the following command:
`CMAKE_ARGS="-DLLAMA_OPENBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir`

But the model still load on my RAM and is executed on CPU. My devcontainer is using the following docker-compose.yml definition:
```
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    init: true
    volumes:
      - .:/workspace:cached
      - llm_models:/workspace/models:cached
    command: sleep infinity
    restart: no
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '24gb'
    environment:
      FORCE_CUDA: 1
      CUDA_VISIBLE_DEVICES: 0

volumes:
  llm_models:
    external: true
```
