### ISSUE TITLE
TogetherAI not working on release 0.1.13 & 0.1.13

### ISSUE THREAD

**Issue by honne23** [guidance-ai/guidance#795]
**The bug**
I've been unable to use models from together.ai due to a 401 error relating to huggingface, despite passing in a valid API key, both as a `api_key` init variable and environment variable `TOGETHERAI_API_KEY`.

**To Reproduce**
#### Dependencies:
```toml
# pyproject.toml

# For version 0.1.12
guidance = { rev="a2df851497d4f54bfd848d3bd198ef1c219e10b5", git="https://github.com/guidance-ai/guidance.git" }

# For version 0.1.13
guidance = { version="0.1.13" }
```
```python
from guidance.models import Model
from guidance import models

# Using the environment variable
os.environ['TOGETHERAI_API_KEY'] = "<together-ai-api-key>"
llm: Model = models.TogetherAI("mistralai/Mixtral-8x7B-Instruct-v0.1")


# passing the key in a param
llm: Model = models.TogetherAI("mistralai/Mixtral-8x7B-Instruct-v0.1", api_key="<together-ai-api-key>")
```

**System info (please complete the following information):**
 - OS: Mac M1 Pro
 - Guidance Version (`guidance.__version__`): 0.1.12 & 0.1.13
